{% set name = "redpil" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fba8a5330bcfd3b8e64f916b3dff323690c2ae341f009d679acc1830cbb7d932

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - numpy

test:
  imports:
    - redpil
    - redpil.bmp

about:
  home: https://github.com/hmaarrfk/redpil
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Join the wonderland of python, and decode all your images in a numpy compatible way'

extra:
  recipe-maintainers:
    - hmaarrfk
